/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 src/assets/models/env/timjorts.glb
Author: crimisya (https://sketchfab.com/crimisya)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/coffee-cup-redux-cc56b844de7d462b94fa91e3d2660e85
Title: Coffee Cup Redux
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Timjorts(props) {
  const { nodes, materials } = useGLTF('./src/assets/models/env/timjorts.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.pCylinder3_cupthing_0.geometry} material={materials.cupthing} position={[-10,4,11]}/>
    </group>
  )
}

useGLTF.preload('./src/assets/models/env/timjorts.glb')
